make: ford,hyundai,kia,maruthi
security:
  ignored: /**
automobile:
  make:
    - hyundai
    - kia
    - Chevrolet
    - Datsun
    - Fiat
    - Ford
    - Honda
    - Isuzu
    - Jeep
    - Mahindra
    - Maruti Suzuki
    - MG Motors
    - Mitsubishi
    - Nissan
    - Renault
    - Skoda
    - Ssangyong
    - Tata
    - Toyata
    - Volkswagen
  models:
    hyundai:
      - verna
      - creta
    kia:
      - seltos
      - sonet
server:
  port: 8081
  servlet:
    context-path: /external
