spring:
  data:
    mongodb:
      uri: mongodb+srv://nai:pass@nai-v5nji.gcp.mongodb.net/test?retryWrites=true&w=majority
make: ford,hyundai,kia,maruthi

automobile:
  make:
    - hyundai
    - kia
  models:
    hyundai:
      - verna
      - creta
    kia:
      - seltos
      - sonet