automobile:
  color:
    - White
    - Black
    - Silver
    - Red
    - Blue
    - Grey
    - Beige
    - Brown
    - Yellow
    - Green
    - Purple
    - Maroon
  bodytype:
    - Sedan
    - Hatch
    - Coupe
    - Luxury
    - Wagon
    - SUV
    - XUV
    - MUV
  fueltype:
    - Petrol
    - Diesel
    - Electric
    - CNG
  transmission:
    - Automatic
    - Manual



spring:
  data:
    mongodb:
      uri: mongodb+srv://nai:pass@nai-v5nji.gcp.mongodb.net/test?retryWrites=true&w=majority
server:
  port: 8080
