make: ford,hyundai,kia,maruthi
automobile:
  make:
    - hyundai
    - kia
    - Chevrolet
    - Datsun
    - Fiat
    - Ford
    - Honda
    - Isuzu
    - Jeep
    - Mahindra
    - Maruti Suzuki
    - MG Motors
    - Mitsubishi
    - Nissan
    - Renault
    - Skoda
    - Ssangyong
    - Tata
    - Toyata
    - Volkswagen
  models:
    hyundai:
      - verna
      - creta
    kia:
      - seltos
      - sonet
spring:
  data:
    mongodb:
      uri: ${DATA_SOURCE}
server:
  port: 8080
